export const legalEntities = {
  series: {
    text: 'Series LLC (formed instantly!)',
    template: 'https://gateway.pinata.cloud/ipfs/QmUDZw3ALFXcbHvUseyjLeq8AbXDrQwfrwCdgL6XngiNnt',
    docs: '',
    email: true,
    mission: false,
    message:
      'Your series will be formed instantly, but we need to follow up to request information we must keep on file for your series.',
  },
  delawareUNA: {
    text: 'Delaware UNA (formed instantly!)',
    template: 'https://gateway.pinata.cloud/ipfs/QmSEEcunxFs8oRQbPaoeV2pYBYJihpZUx6QYUsUqc89Gci',
    docs: 'UNA',
    email: false,
    mission: true,
    message: null,
  },
  verein: {
    text: 'Swiss Verein (formed instantly!)',
    template: null,
    docs: 'none',
    email: true,
    mission: false,
    message: 'We will contact you to provide options for registering a Swiss Verein and the associated costs.',
  },
  delawareLLC: {
    text: 'Delaware LLC (est. 1-2 weeks)',
    template: null,
    docs: 'none',
    email: true,
    mission: false,
    message: 'We will contact you to provide options for registering a Delaware LLC and the associated costs.',
  },
  wyomingLLC: {
    text: 'Wyoming LLC (est. 1-2 weeks)',
    template: null,
    docs: 'none',
    email: true,
    mission: false,
    message: 'We will contact you to provide options for registering a Wyoming LLC and the associated costs.',
  },
  custom: {
    text: 'Custom Entity Type (est. TBD)',
    template: null,
    docs: 'none',
    email: true,
    mission: false,
    message: 'We will contact you to provide options for your desired entity type and the associated costs.',
  },
  existing: {
    text: 'Existing Entity',
    template: null,
    docs: 'none',
    email: false,
    mission: false,
    input: true,
    message: 'The provided document will be linked to your DAO.',
  },
}
