export const serviceProviders = [
  {
    name: 'LexDAO Clinic',
    text: 'Law students and pros from around the world sort your legals',
    link: 'https://j6dn81d0m26.typeform.com/to/BXwMVdWX',
    icon: null,
    diy: false,
  },
  {
    name: 'Doola',
    text: 'Fill out a form and get a US LLC and bank account',
    link: 'https://doolahq.typeform.com/kalixdoola',
    icon: null,
    diy: false,
  },
  {
    name: 'Opolis',
    text: 'Get insurance and other IRL benefits',
    link: 'https://connect.opolis.co/kali/',
    icon: null,
    diy: false,
  },
  {
    name: 'Twali',
    text: 'Decentralized expert marketplace.',
    link: 'https://twali.xyz/',
    icon: '/img/services/twali.svg',
    diy: false,
  },
  {
    name: 'Multis',
    text: "Manage your DAO's crypto finances",
    link: 'https://app.multis.finance/signin',
    icon: '/img/services/multis.svg',
    diy: false,
  },
  {
    name: 'BlockApex',
    text: 'Security services and financial risk assessment',
    link: 'https://blockapex.io/',
    icon: '/img/services/blockApex.svg',
    diy: false,
  },
  {
    name: 'IRS',
    text: 'Portal to apply for an EIN for your KaliDAO',
    link: 'https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online',
    icon: null,
    diy: true,
  },
]
