// /*
//   Auto-generated by Spline
// */

// import useSpline from '@splinetool/r3f-spline'
// import { OrthographicCamera } from '@react-three/drei'

// export default function Scene({ ...props }) {
//   const { nodes, materials } = useSpline('https://prod.spline.design/nDco9eJtMLZhIVdm/scene.splinecode')
//   return (
//     <>
//       <color attach="background" args={['#210023']} />
//       <group {...props} dispose={null}>
//         <mesh
//           name="Merged Geometry 2"
//           geometry={nodes['Merged Geometry 2'].geometry}
//           material={materials['Merged Geometry 2 Material']}
//           castShadow
//           receiveShadow
//           position={[-350.72, -158.01, -81]}
//         />
//         <mesh
//           name="Sphere"
//           geometry={nodes.Sphere.geometry}
//           material={materials['Sphere Material']}
//           castShadow
//           receiveShadow
//           position={[2.5, -6.5, 189.5]}
//         />
//         <directionalLight
//           name="Directional Light"
//           castShadow
//           intensity={4.57}
//           shadow-mapSize-width={1024}
//           shadow-mapSize-height={1024}
//           shadow-camera-near={-10000}
//           shadow-camera-far={100000}
//           shadow-camera-left={-591.474}
//           shadow-camera-right={591.474}
//           shadow-camera-top={591.474}
//           shadow-camera-bottom={-591.474}
//           position={[100, -13453.94, -28879.2]}
//           rotation={[-1.92, -0.9, -1.72]}
//           scale={[-108.64, 9.76, 0.57]}
//         />
//         <OrthographicCamera
//           name="Personal Camera"
//           makeDefault={true}
//           zoom={0.49}
//           far={100000}
//           near={-100000}
//           up={[0, -1, 0]}
//           position={[5476.35, 5395.37, 5442.44]}
//           rotation={[-Math.PI / 4, 0.62, -2.62]}
//         />
//         <hemisphereLight name="Default Ambient Light" intensity={0.77} color="#feb8b8" position={[0, 1, 0]} />
//       </group>
//     </>
//   )
// }
